site_name: "Sree Devi’s Documentation on Virtual Machines, Docker & Networking"
site_url: https://sreedevirajavelu.github.io/VirtualMachines/
theme:
  name: material
site_dir: site
use_directory_urls: true
repo_url: https://github.com/SreedeviRajavelu/VirtualMachines
repo_name: GitHub
nav:
  - Docker, Virtual Machines & Networks: index.md
  - Docker:
      - Docker Build: DockerBuild.md
      - Docker Networking: Docker_Networks.md
      - Docker Macvlan Network: Docker_Macvlan_Network.md
      - Docker Engine on Ubuntu: DockerEngine_Ubuntu.md
      - Communication Inside & Outside Docker: CommunicationBetweenInsideAndOutsideDocker.md
      - Docker Container Interfaces: Docker_Container_Interfaces.md
      - Using tarballs (.tgz): Docker_tgz.md
      - Docker Compose: Docker_Compose.md
      - Docker Volumes: Docker_Volumes.md
  - Virtualization:
      - VM-to-VM Communication: VM-to-VM-Communication.md
      - Fix Slow Ubuntu VM Boot: Fix_Slow_UbuntuVM_Boot.md
      - Recovering VM: Recovering_VM.md
  - Tools:
      - SSH: SSH.md
      - Matlab: Matlab.md
      - Matlab Docker: Matlab_Docker.md
      - Wine: Wine.md
      - SQL: SQL.md 
      - PostgreSQL: PostgreSQL.md
      - Matlab Data Sources: Matlab_Data_Sources.md
      - Remote Port Fowarding SSH: Remote_PortForwarding_SSH.md
      - NAT Adapter Iptables Fowarding: NAT_Adapter_Iptables_Forwarding.md
      - Bridged Adapter : Bridged_Adapter.md
      - File Transfer Host To Remote: File_Transfer_Host_To_Remote.md
      - Systemctl Systemd: Systemctl_Systemd.md
  - SCADA:
      - ScadaLTS: ScadaLTS.md
  - OS:
      - Mac Notes: Mac.md
  - System Administration:
      - Linux System Administration: Linux_System_Administration.md
      - Networking Fundamentals: Networking_Fundamentals.md
      - Troubleshooting Tools: Troubleshooting_Tools.md